# Name your project! Project names should contain only lowercase characters and underscores. 
# A good package name should reflect your organization's name or the intended use of these models

# References:
#   [0] https://docs.getdbt.com/docs/build/projects
#   [1] https://docs.getdbt.com/reference/model-configs

name: 'my_dbt_project'
version: '1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'duckdb_profile' # Make sure this matches the name in profiles.yml

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]       # Directories to where your model and source files live
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]       
macro-paths: ["macros"] 
snapshot-paths: ["snapshots"]

target-path: 'target' # directory which will store compiled SQL files

clean-targets:        # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:  # [1]
  my_dbt_project:  
    s3_bucket:
      # +schema: bronze # If you want the 'dbt_caio' schema (defined in profiles.yml) to be created with 'dbt run', then do not use this '+schema:'
      +materialized: 'table'  # Configured to create tables in the bronze schema 